name: skin_analyzer
description: Приложение для анализа состояния кожи и косметики
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.30.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  image_picker: ^0.8.7
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  camera: ^0.10.5
  path_provider: ^2.0.14
  path: ^1.8.3
  flutter_markdown: ^0.6.14
  intl: ^0.17.0
  fl_chart: ^0.65.0
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/